package internshipManagerDAL.Entities;
// Generated 2-jun-2018 13:00:17 by Hibernate Tools 4.3.1


import internshipManagerBO.Services.InternshipServices;
import java.util.Calendar;
import java.util.Date;

/**
 * Internship generated by hbm2java
 */
public class Internship  implements java.io.Serializable {


     private Integer id;
     private Organisation organisation;
     private String title;
     private String description;
     private Date startDate;

    public Internship() {
    }

    public Internship(Organisation organisation, String title, String description, Date startDate) {
       this.organisation = organisation;
       this.title = title;
       this.description = description;
       this.startDate = startDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Organisation getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    @Override
    public String toString() {
        InternshipServices service = new InternshipServices();
        String organisationName = service.getInternshipOrganisationName(this.id);
        String startDate = service.transformDateToString(this.startDate);
        return this.title + ", " + organisationName + " - Startdate: " + startDate;
    }
    
    public String searchify() {
        String searchifiedInternship = "";
        String stringifiedStartDate = "";
        String searchifiedOrganisation = "";
        InternshipServices service = new InternshipServices();
        searchifiedOrganisation = service.getInternshipOrganisationSearchified(this.id);
        stringifiedStartDate = service.transformDateToString(this.startDate);
        searchifiedInternship = this.title + stringifiedStartDate + searchifiedOrganisation;
        return searchifiedInternship.toLowerCase();
    }




}


