package internshipManagerDAL.Entities;
// Generated 2-jun-2018 13:00:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organisation generated by hbm2java
 */
public class Organisation  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String streetAddress;
     private String zipCode;
     private String city;
     private String contactPerson;
     private String email;
     private Set internships = new HashSet(0);

    public Organisation() {
    }

	
    public Organisation(String name, String streetAddress, String zipCode, String city, String contactPerson, String email) {
        this.name = name;
        this.streetAddress = streetAddress;
        this.zipCode = zipCode;
        this.city = city;
        this.contactPerson = contactPerson;
        this.email = email;
    }
    public Organisation(String name, String streetAddress, String zipCode, String city, String contactPerson, String email, Set internships) {
       this.name = name;
       this.streetAddress = streetAddress;
       this.zipCode = zipCode;
       this.city = city;
       this.contactPerson = contactPerson;
       this.email = email;
       this.internships = internships;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStreetAddress() {
        return this.streetAddress;
    }
    
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getInternships() {
        return this.internships;
    }
    
    public void setInternships(Set internships) {
        this.internships = internships;
    }




}


